std = "testez"

[lints]
almost_swapped = "deny"
constant_table_comparison = "deny" # 1
deprecated = "deny"
divide_by_zero = "deny"
duplicate_keys = "deny"
empty_if = "deny" # 2
empty_loop = "deny"
global_usage = "deny"
high_cyclomatic_complexity = "warn"
if_same_then_else = "deny"
if_same_cond = "deny"
incorrect_standard_library_use = "deny"
manual_table_clone = "deny"
mismatched_arg_count = "deny"
mixed_table = "deny"
multiple_statements = "deny"
must_use = "deny"
parenthese_conditions = "deny"
restricted_module_paths = "warn"
roblox_incorrect_color3_new_bounds = "deny"
roblox_incorrect_roact_usage = "deny"
roblox_manual_fromscale_or_fromoffset = "deny"
roblox_suspicious_udim2_new = "deny"
shadowing = "deny"
suspicious_reverse_loop = "deny"
type_check_inside_call = "deny"
unbalanced_assignments = "deny"
undefined_variable = "deny"
unscoped_variables = "deny"
unused_variable = "deny"
