syntax = "Luau"
column_width = 120
indent_type = "Tabs"
quote_style = "ForceDouble"
call_parentheses = "Always"
space_after_function_names = "Never"
block_newline_gaps = "Never"
collapse_simple_statement = "Never"
